((daiso . ((note . "DAISO ナンプレ") (path . "./boards/daiso/daiso.scm")))
 (magazine1 . ((note . "ナンプレ雑誌 STAGE1") (path . "./boards/magazine/magazine1.scm")))
 (magazine2 . ((note . "ナンプレ雑誌 STAGE2") (path . "./boards/magazine/magazine2.scm")))
 (magazine3 . ((note . "ナンプレ雑誌 STAGE3") (path . "./boards/magazine/magazine3.scm")))
 (magazinec . ((note . "ナンプレ雑誌 CHALLENGE") (path . "./boards/magazine/magazinec.scm")))
 (magazine4 . ((note . "ナンプレ雑誌 STAGE4") (path . "./boards/magazine/magazine4.scm")))
 (magazine5 . ((note . "ナンプレ雑誌 STAGE5") (path . "./boards/magazine/magazine5.scm")))
 (magazine6 . ((note . "ナンプレ雑誌 STAGE6") (path . "./boards/magazine/magazine6.scm"))))
